---
# Variable configuration
- ansible.builtin.include_tasks: ./variables.yaml

# Setup/install tasks.
#- ansible.builtin.include_tasks: setup-RedHat.yml
#  when: ansible_os_family == 'RedHat'

#- ansible.builtin.include_tasks: setup-Debian.yml
#  when: ansible_os_family == 'Debian'

#- ansible.builtin.include_tasks: setup-Archlinux.yml
#  when: ansible_os_family == 'Archlinux'

- name: Check if MySQL packages were installed.
  ansible.builtin.set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"

# Configure MySQL.
- ansible.builtin.include_tasks: configure.yaml
- ansible.builtin.include_tasks: secure-installation.yaml
- ansible.builtin.include_tasks: databases.yaml
- ansible.builtin.include_tasks: users.yaml
# - ansible.builtin.include_tasks: replication.yml
