name: pre-commit

on:
  pull_request:
    branches: [main]  # triggers when a PR is opened to main
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # important: get full history for pre-commit to work properly

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.27.0/gitleaks_8.27.0_linux_x64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/
          gitleaks version

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
